name: Tests

on:
  push:
    branches:
    - "master"
    - "main"
  pull_request:

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
    - name: Lint
      uses: ricardochaves/python-lint@v1.4.0
      with:
        use-pylint: false
        use-pycodestyle: false
        use-flake8: false
        use-black: true
        use-mypy: false
        use-isort: false